[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "openai>=1.97.0",
    "pytz>=2025.2",
    "requests>=2.32.4",
    "flask>=2.3.3"
]